name: Build qtwebengine-bin
on: workflow_dispatch
  # schedule:
  #   - cron: '0 0 * * *'
jobs:
  build-qtwebengine-bin:
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache binpkgs
        uses: actions/cache@v2
        with:
          path: ~/.portage-pkgdir
          key: portage-pkgdir-${{ github.run_number }}
          restore-keys: |
            portage-pkgdir-
      - run: ./build.sh
